[package]
name = "openimageio-sys"
version = "0.1.0"
authors = ["Alexandre Bl√©ron <alex.bleron@gmail.com>"]
build = "build.rs"

[dependencies]

[build-dependencies]
vcpkg = "*"
pkg-config = "*"
bindgen = "*"
gcc = "*"
