[package]
name = "openimageio-sys"
version = "0.1.0"
authors = ["Alexandre Bl√©ron <alex.bleron@gmail.com>"]
build = "build.rs"
edition = "2018"

[dependencies]
libc = "*"

[build-dependencies]
vcpkg = "0.2.7"
pkg-config = "0.3.16"
bindgen = "0.51.1"
cc = "1.0.45"
